version: "3.9"

services:

  xumak-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8190:8080"
    networks:
      - xumak-network
    links:
      - xumak-db


  xumak-db:
    image: postgres:10.21-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - xumak-network

volumes:
  db:
    driver: local

networks:
  xumak-network: