version: "3.9"

services:
  xumak-db:
    image: postgres:10.21-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local