apiVersion: v1
kind: Service
metadata:
  labels:
    app: xumak-app
  name: xumak-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: xumak-app
  type: NodePort